services:
  samba-service:
      image: "wbclient-service-image"
      container_name: wbclient-service
      ports:
        - "${WBCLIENT_PORT:-8080}:${WBCLIENT_PORT:-8080}"
      dns:
        - ${DC_IP}
      dns_search:
        - ${DOMAIN_NAME}
      volumes:
        - ../../:/usr/src/wbclient
        - go-modules-svc:/root/go/pkg/mod
        - go-cache-svc:/root/.cache
        - samba-config:/etc/samba
        - samba-private:/var/lib/samba/private
        - samba-logs:/var/log/samba
        - /sys/fs/cgroup:/sys/fs/cgroup:rw
        - /etc/localtime:/etc/localtime:ro
      privileged: true
      environment:
        - WBCLIENT_API_TOKEN=${WBCLIENT_API_TOKEN}
        - WBCLIENT_PORT=${WBCLIENT_PORT:-8080}
      tty: true
      stdin_open: true
      stop_signal: SIGRTMIN+3
      tmpfs:
        - /run
        - /run/lock
volumes:
    go-modules-svc: {}
    go-cache-svc: {}
    samba-config: {}
    samba-private: {}
    samba-logs: {}
